---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian8

script:
  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
