---
- template:
    src: templates/loopdev.init.j2
    dest: "/etc/init.d/{{ item.name }}"
    owner: root
    group: root
    mode: 0755
  become: true
  with_items:
    "{{ losetup }}"

- name: diskloop | Ensuring disk is running
  service:
    name: "{{ item.name }}"
    enabled: true
  become: true
  with_items:
    "{{ losetup }}"
