---
- name: prepare redhat | Installing python-selinux
  raw: test -e /usr/bin/yum && (yum install -y libselinux-python)
  ignore_errors: yes
  register: output
  changed_when: output.stdout != ""
  become: true
- setup:
